const minasForma = "/images/minasForma.svg";
const rep = "/images/rep.webp";
const gs3 = "/images/gs3.png";
const navia = "/images/navia3.png";


const ProjectsData = [
    {
        name: "Minas Forma, Minas Transforma",
        image: minasForma,
        link: "https://minas-forma-minas-transforma-git-demo-smarthow.vercel.app/entrar",
        description: "Web platform developed by me and used by the secretariat of culture of Minas Gerais (SECULT), for management, control and professional training of demands generated by the municipalities.",
        i18nKey: "minasDesc",
        projectLanguage1: "Next JS",
        projectLanguage2: "Tailwind",
        projectLanguage3: "Firebase"

    },
    {
        name: "Geotechnical Structures Safety System",
        image: gs3,
        link: "https://sa-east-1uiauhbtvd.auth.sa-east-1.amazoncognito.com/login?client_id=jf0pu8oo6i8088tmair4cjpog&nonce=PjeURzSYA9qIZ-VX6K5XGPGrAQaPI1g_dc6vqmcuDNg&redirect_uri=https://api-v2.gs3tellus.com.br/v1/auth/callback&response_type=code&scope=openid+email&state=FWjXaVor_PBHb51a3AdpCTF0ZKD0oIM8TWAa6wRzViI",
        description: "Geotechnical and structural monitoring software to centralize instrument data, stability analysis, time series analysis, and trigger alarms with speed and traceability, among other features.",
        i18nKey: "gs3Desc",
        projectLanguage1: "React JS",
        projectLanguage2: "GraphQL",
        projectLanguage3: "Styled Components"

    },
    {
        name: "NAVIA",
        image: navia,
        link: "https://app.naviasistemas.com.br/sign-in",
        description: "Navia is a complete management platform designed to connect consultants and clients efficiently. Our solution centralizes projects, simplifies processes, and facilitates communication, offering everything you need to scale your consultancy and deliver results with excellence and transparency.",
        i18nKey: "naviaDesc",
        projectLanguage1: "Next JS",
        projectLanguage2: "GraphQL",
        projectLanguage3: "Tailwind"
    },
    {
        name: "Repmov Brasil",
        image: rep,
        link: "https://repmov.com/",
        description: "Application developed in flutter framework and with database in firebase. Mobile platform with multiple functionality such as airline tickets, hotels, digital banking and its main function comes with urban mobility.",
        i18nKey: "repDesc",
        projectLanguage1: "Flutter",
        projectLanguage2: "Firebase",
        projectLanguage3: "Dart",
    },


]

export default ProjectsData;